[package]
name = "DRIT"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
windows-sys = { version = "0.61.2", features = ["Win32_UI_Input_KeyboardAndMouse"] }
[build-dependencies]
winres = "0.1.12"